/**
 * gameData.js
 * Static game data for the GameGallery, sourced from games_dataset.csv.
 * This is a frontend-only representation — the CSV and backend are NOT modified.
 */

const GAMES = [
  {
    id: 101,
    title: "Uncharted: Legacy of Thieves Collection",
    description:
      "Seek your fortune and leave your mark on the map in a globe-trotting cinematic action-adventure filled with high-stakes thrills.",
    tags: ["Action", "Adventure", "Cinematic", "Treasure Hunting"],
    genre: "Action",
    price: 3299,
    minRam: 8,
    minGpuTier: 3,
    steamAppId: 1659420,
    image: "/images/uncharted.png",
  },
  {
    id: 102,
    title: "Cities: Skylines",
    description:
      "A modern take on the classic city simulation. Realize the thrill and hardships of creating and maintaining a real city with complex economies.",
    tags: ["City Builder", "Simulation", "Management", "Sandbox"],
    genre: "Simulation",
    price: 850,
    minRam: 4,
    minGpuTier: 2,
    steamAppId: 255710,
    image: "/images/cities_skylines.png",
  },
  {
    id: 103,
    title: "Forza Horizon 5",
    description:
      "Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless driving action in the world's greatest cars.",
    tags: ["Racing", "Open World", "Driving", "Multiplayer"],
    genre: "Racing",
    price: 3499,
    minRam: 8,
    minGpuTier: 4,
    steamAppId: 1551360,
    image: "/images/forza_horizon_5.png",
  },
  {
    id: 104,
    title: "Resident Evil 4",
    description:
      "Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City, and a new terrifying rescue mission awaits.",
    tags: ["Horror", "Survival", "Zombies", "Shooter"],
    genre: "Horror",
    price: 3599,
    minRam: 8,
    minGpuTier: 4,
    steamAppId: 2050650,
    image: "/images/resident_evil_4.png",
  },
  {
    id: 105,
    title: "Slay the Spire",
    description:
      "We fused card games and roguelikes together to make the best single player deckbuilder we could. Climb the spire and conquer your foes.",
    tags: ["Deckbuilder", "Roguelike", "Card Game", "Strategy"],
    genre: "Strategy",
    price: 899,
    minRam: 2,
    minGpuTier: 1,
    steamAppId: 646570,
    image: "/images/slay_the_spire.png",
  },
  {
    id: 106,
    title: "Tekken 8",
    description:
      "Get ready for the next chapter in the legendary fighting game franchise, featuring brand new mechanics and stunning next-gen visuals.",
    tags: ["Fighting", "Martial Arts", "Competitive", "Arcade"],
    genre: "Fighting",
    price: 4199,
    minRam: 8,
    minGpuTier: 4,
    steamAppId: 1778820,
    image: "/images/tekken_8.png",
  },
  {
    id: 107,
    title: "Celeste",
    description:
      "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain in this super-tight, narrative-driven platformer.",
    tags: ["Platformer", "Pixel Graphics", "Difficult", "Story Rich"],
    genre: "Platformer",
    price: 529,
    minRam: 2,
    minGpuTier: 1,
    steamAppId: 504230,
    image: "/images/celeste.png",
  },
  {
    id: 108,
    title: "Crusader Kings III",
    description:
      "Guide a royal dynasty through the centuries in this grand strategy epic. Secure your bloodline through diplomacy, war, and political marriages.",
    tags: ["Grand Strategy", "Historical", "Simulation", "RPG"],
    genre: "Strategy",
    price: 1699,
    minRam: 6,
    minGpuTier: 2,
    steamAppId: 1158310,
    image: "/images/crusader_kings.png",
  },
  {
    id: 109,
    title: "Overcooked! 2",
    description:
      "Journey back to the Onion Kingdom and assemble your team of chefs in chaotic couch co-op where communication is the only recipe for success.",
    tags: ["Co-op", "Cooking", "Casual", "Family Friendly"],
    genre: "Casual",
    price: 850,
    minRam: 4,
    minGpuTier: 1,
    steamAppId: 728880,
    image: "/images/overcooked_2.png",
  },
  {
    id: 110,
    title: "Return of the Obra Dinn",
    description:
      "An insurance adventure with minimal color. In 1802, a merchant ship washed into port with no crew. You must deduce what happened to them all.",
    tags: ["Puzzle", "Detective", "Mystery", "Retro"],
    genre: "Puzzle",
    price: 529,
    minRam: 4,
    minGpuTier: 1,
    steamAppId: 653530,
    image: "/images/obra_dinn.png",
  },
  {
    id: 111,
    title: "GTA V",
    description:
      "An action-packed open-world adventure set in the sprawling city of Los Santos. Explore a massive map, engage in thrilling heists, and experience a gripping crime drama.",
    tags: ["Action", "Open World", "Adventure", "Crime", "Driving", "Multiplayer"],
    genre: "Action",
    price: 999,
    minRam: 8,
    minGpuTier: 3,
    steamAppId: 271590,
    image: "/images/gta_v.png",
  },
  {
    id: 112,
    title: "Valorant",
    description:
      "A highly competitive 5v5 tactical first-person shooter where precise gunplay meets unique agent abilities. Choose from a diverse roster of agents.",
    tags: ["FPS", "Multiplayer", "Competitive", "Tactical Shooter", "Team-Based"],
    genre: "FPS",
    price: 0,
    minRam: 4,
    minGpuTier: 2,
    steamAppId: 0,
    image: "/images/valorant.png",
  },
  {
    id: 113,
    title: "The Witcher 3",
    description:
      "Embark on a grand open-world adventure as Geralt of Rivia, a monster hunter searching for his adopted daughter in a war-torn fantasy realm.",
    tags: ["RPG", "Open World", "Story Rich", "Adventure", "Fantasy", "Action"],
    genre: "RPG",
    price: 1499,
    minRam: 8,
    minGpuTier: 3,
    steamAppId: 292030,
    image: "/images/witcher_3.png",
  },
  {
    id: 114,
    title: "Stardew Valley",
    description:
      "Escape to the countryside and build the farm of your dreams in this charming indie simulation. Plant crops, raise animals, and build relationships.",
    tags: ["Simulation", "Indie", "Chill", "Farming", "Relaxing", "Sandbox"],
    genre: "Simulation",
    price: 499,
    minRam: 4,
    minGpuTier: 1,
    steamAppId: 413150,
    image: "/images/stardew_valley.png",
  },
  {
    id: 115,
    title: "Cyberpunk 2077",
    description:
      "Dive into the neon-soaked open world of Night City in this action-packed RPG. Customize your character and explore a sprawling futuristic metropolis.",
    tags: ["RPG", "Open World", "Sci-Fi", "Action", "Adventure", "FPS", "Story Rich"],
    genre: "RPG",
    price: 2999,
    minRam: 12,
    minGpuTier: 4,
    steamAppId: 1091500,
    image: "/images/cyberpunk_2077.png",
  },
  {
    id: 116,
    title: "Minecraft",
    description:
      "The ultimate open-world sandbox adventure where creativity knows no bounds. Build anything, explore vast worlds, and survive against hostile creatures.",
    tags: ["Sandbox", "Survival", "Creative", "Open World", "Adventure", "Multiplayer", "Building"],
    genre: "Sandbox",
    price: 1199,
    minRam: 4,
    minGpuTier: 1,
    steamAppId: 0,
    image: "/images/minecraft.png",
  },
  {
    id: 117,
    title: "Apex Legends",
    description:
      "A fast-paced free-to-play battle royale shooter featuring squad-based gameplay. Drop into the arena and fight to be the last squad standing.",
    tags: ["FPS", "Battle Royale", "Multiplayer", "Action", "Competitive", "Shooter"],
    genre: "FPS",
    price: 0,
    minRam: 8,
    minGpuTier: 3,
    steamAppId: 1172470,
    image: "/images/apex_legends.png",
  },
  {
    id: 118,
    title: "Age of Empires IV",
    description:
      "A real-time strategy game where players build thriving civilizations and lead massive armies to victory across historical campaigns.",
    tags: ["Strategy", "RTS", "Historical", "Simulation", "Warfare", "Competitive"],
    genre: "Strategy",
    price: 1999,
    minRam: 8,
    minGpuTier: 2,
    steamAppId: 1466860,
    image: "/images/age_of_empires.png",
  },
  {
    id: 119,
    title: "Hades",
    description:
      "Fight your way out of the Greek underworld in this award-winning roguelike action game. Battle mythological enemies with fast-paced combat.",
    tags: ["Indie", "Rogue-like", "Action", "Adventure", "Mythology", "Story Rich"],
    genre: "Action",
    price: 569,
    minRam: 8,
    minGpuTier: 2,
    steamAppId: 1145360,
    image: "/images/hades.png",
  },
  {
    id: 120,
    title: "Microsoft Flight Simulator",
    description:
      "Experience the thrill of flight in the most realistic aviation simulator ever created. Fly over breathtaking real-world landscapes.",
    tags: ["Simulation", "Realistic", "Open World", "Flying", "Exploration", "Adventure"],
    genre: "Simulation",
    price: 3999,
    minRam: 16,
    minGpuTier: 5,
    steamAppId: 1250410,
    image: "/images/flight_simulator.png",
  },
];

export default GAMES;
